import type { LucideIcon } from 'lucide-react';
import {
  Activity,
  BadgeCheck,
  BarChart3,
  BookOpen,
  Bot,
  CalendarCheck,
  CheckSquare,
  ClipboardCheck,
  FlaskConical,
  Gauge,
  GitBranch,
  GitMerge,
  Globe,
  LayoutDashboard,
  Library,
  ListTodo,
  MessageSquare,
  Microscope,
  Package,
  Rocket,
  ScrollText,
  Shield,
  UserCog,
  Users,
} from 'lucide-react';

/** Lucide icon per sidebar tab id — keys must match `splm-navigation.ts` `tabId`. */
export const SPLM_NAV_TAB_ICONS: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  queue: ListTodo,
  products: Package,
  tasks: CheckSquare,
  sprints: Gauge,
  versions: GitBranch,
  feedback: MessageSquare,
  research: Microscope,
  wiki: BookOpen,
  deployments: Rocket,
  environments: Globe,
  releases: CalendarCheck,
  'ai-overview': Activity,
  workflow: GitMerge,
  'qa-cycles': FlaskConical,
  'ai-analyzer': Bot,
  'fix-review': ClipboardCheck,
  canary: Rocket,
  'pm-signoff': ClipboardCheck,
  'pdm-signoff': BadgeCheck,
  'prompt-library': Library,
  'kpi-dashboard': BarChart3,
  team: Users,
  'user-management': UserCog,
  rbac: Shield,
  'audit-logs': ScrollText,
};
